[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$BackendUrl,
    [string]$PythonPath = "",
    [switch]$AllowHttp
)

$ErrorActionPreference = "Stop"
$InstallerDir = $PSScriptRoot
$ConnectorRoot = Split-Path -Parent $InstallerDir
$ToolsDir = Join-Path $InstallerDir "tools"
$DistDir = Join-Path $ConnectorRoot "dist"
$SpecFile = Join-Path $InstallerDir "onevo-connector.spec"
$IssFile = Join-Path $InstallerDir "onevo-connector.iss"
$BakedFile = Join-Path $ConnectorRoot "app\baked_config.py"
$WinSwConfig = Join-Path $InstallerDir "winsw\onevo-connector-service.xml"

function Assert-BackendUrl([string]$Url, [bool]$AllowHttp) {
    $u = $Url.Trim().TrimEnd("/")
    if ($u -match '^https://') { return $u }
    if ($u -match '^http://(localhost|127\.0\.0\.1)(:\d+)?(/.*)?$') { return $u }
    if ($AllowHttp -and $u -match '^http://') { return $u }
    throw "Production requires HTTPS (or http://localhost / http://127.0.0.1 for local builds). Got: $Url. Use -AllowHttp for MVP pilot without TLS."
}

function Find-ISCC {
    $candidates = @(
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
        "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe",
        (Get-Command ISCC -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source)
    ) | Where-Object { $_ -and (Test-Path $_) }
    if (-not $candidates) {
        throw "Inno Setup 6 (ISCC.exe) was not found. Install from https://jrsoftware.org/isdl.php"
    }
    return ($candidates | Select-Object -First 1)
}

function Find-Python([string]$ExplicitPath) {
    $candidates = @(
        $ExplicitPath,
        $env:ONEVO_PYTHON,
        $env:PYTHON_EXE,
        (Get-Command python -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
        "$env:LOCALAPPDATA\Python\bin\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python314\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python313\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe"
    )
    $userRoots = Get-ChildItem 'C:\Users' -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -notin @('Public', 'Default', 'Default User', 'All Users') }
    foreach ($user in $userRoots) {
        $candidates += @(
            (Join-Path $user.FullName 'AppData\Local\Python\bin\python.exe'),
            (Join-Path $user.FullName 'AppData\Local\Programs\Python\Python314\python.exe'),
            (Join-Path $user.FullName 'AppData\Local\Programs\Python\Python313\python.exe'),
            (Join-Path $user.FullName 'AppData\Local\Programs\Python\Python312\python.exe'),
            (Join-Path $user.FullName 'AppData\Local\Programs\Python\Python311\python.exe')
        )
    }
    $found = $candidates | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
    if (-not $found) {
        throw "Python was not found. Set ONEVO_PYTHON or install Python 3.11+ and add it to PATH."
    }
    return $found
}

$BackendUrl = Assert-BackendUrl $BackendUrl $AllowHttp.IsPresent
Write-Host "==> BackendUrl (baked): $BackendUrl"

$ffmpeg = Join-Path $ToolsDir "ffmpeg.exe"
$winsw = Join-Path $ToolsDir "WinSW-x64.exe"
if (-not (Test-Path $ffmpeg)) { throw "Missing $ffmpeg. See installer/tools/README.md" }
if (-not (Test-Path $winsw)) { throw "Missing $winsw. See installer/tools/README.md" }
if (-not (Test-Path $WinSwConfig)) { throw "Missing $WinSwConfig" }

try {
    [xml](Get-Content -LiteralPath $WinSwConfig -Raw) | Out-Null
} catch {
    throw "Invalid WinSW XML ($WinSwConfig): $($_.Exception.Message)"
}

$python = Find-Python $PythonPath
Write-Host "==> Python: $python"

$baked = @"
# AUTO-GENERATED by installer/build.ps1 - do not edit by hand.
BAKED_BACKEND_URL = "$BackendUrl"
BAKED_AT_BUILD = True
"@
Set-Content -Path $BakedFile -Value $baked -Encoding UTF8
Write-Host "==> Wrote $BakedFile"

New-Item -ItemType Directory -Force -Path $DistDir | Out-Null
$pyinstallerOut = Join-Path $DistDir "onevo-connector.exe"
if (Test-Path $pyinstallerOut) { Remove-Item $pyinstallerOut -Force }

Write-Host "==> PyInstaller deps..."
& $python -m pip install -q -r (Join-Path $ConnectorRoot "requirements.txt") -r (Join-Path $ConnectorRoot "requirements-build.txt")

Write-Host "==> PyInstaller..."
Push-Location $ConnectorRoot
try {
    & $python -m PyInstaller --noconfirm --clean --distpath $DistDir --workpath (Join-Path $DistDir "build") $SpecFile
    if ($LASTEXITCODE -ne 0) {
        throw "PyInstaller build failed (exit $LASTEXITCODE). Ensure pip install -r requirements-build.txt was run."
    }
} finally {
    Pop-Location
}
if (-not (Test-Path $pyinstallerOut)) {
    throw "PyInstaller build failed. Expected output: $pyinstallerOut"
}
Write-Host "==> Built $pyinstallerOut"

$iscc = Find-ISCC
Write-Host "==> Inno Setup: $iscc"
& $iscc $IssFile
if ($LASTEXITCODE -ne 0) { throw "Inno Setup failed (exit $LASTEXITCODE)" }

$verLine = Select-String -Path $IssFile -Pattern '#define AppVersion "([^"]+)"' | Select-Object -First 1
$version = if ($verLine) { $verLine.Matches.Groups[1].Value } else { "1.0.0" }
$setup = Join-Path $DistDir "ONEVO-Connector-Setup-$version.exe"
if (-not (Test-Path $setup)) { throw "Expected installer not found: $setup" }

Write-Host ""
Write-Host "OK  $setup"
Write-Host "    Size: $([math]::Round((Get-Item $setup).Length / 1MB, 1)) MB"
Write-Host "    Copy this file where ConnectorInstaller__Path points (or leave in connector/dist for Docker)."
