[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$BackendUrl
)

$ErrorActionPreference = "Stop"
$InstallerDir = $PSScriptRoot
$ConnectorRoot = Split-Path -Parent $InstallerDir
$ToolsDir = Join-Path $InstallerDir "tools"
$DistDir = Join-Path $ConnectorRoot "dist"
$SpecFile = Join-Path $InstallerDir "onevo-connector.spec"
$IssFile = Join-Path $InstallerDir "onevo-connector.iss"
$BakedFile = Join-Path $ConnectorRoot "app\baked_config.py"
$WinSwConfig = Join-Path $InstallerDir "winsw\onevo-connector-service.xml"

function Assert-BackendUrl([string]$Url) {
    $u = $Url.Trim().TrimEnd("/")
    $parsed = $null
    if (-not [Uri]::TryCreate($u, [UriKind]::Absolute, [ref]$parsed)) {
        throw "Backend URL must be an absolute URL. Got: $Url"
    }
    if ($parsed.UserInfo) {
        throw "Backend URL must not contain embedded credentials. Got: $Url"
    }
    if ($parsed.Scheme -eq "https") { return $parsed.AbsoluteUri.TrimEnd("/") }
    if ($parsed.Scheme -eq "http" -and $parsed.IsLoopback) {
        return $parsed.AbsoluteUri.TrimEnd("/")
    }
    throw "Production requires HTTPS (or http://localhost / http://127.0.0.1 for local builds). Got: $Url"
}

function Find-ISCC {
    $candidates = @(
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
        "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe",
        (Get-Command ISCC -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source)
    ) | Where-Object { $_ -and (Test-Path $_) }
    if (-not $candidates) {
        throw "Inno Setup 6 (ISCC.exe) was not found. Install from https://jrsoftware.org/isdl.php"
    }
    return ($candidates | Select-Object -First 1)
}

$BackendUrl = Assert-BackendUrl $BackendUrl
Write-Host "==> BackendUrl (baked): $BackendUrl"

$ffmpeg = Join-Path $ToolsDir "ffmpeg.exe"
$winsw = Join-Path $ToolsDir "WinSW-x64.exe"
if (-not (Test-Path $ffmpeg)) { throw "Missing $ffmpeg. See installer/tools/README.md" }
if (-not (Test-Path $winsw)) { throw "Missing $winsw. See installer/tools/README.md" }
if (-not (Test-Path $WinSwConfig)) { throw "Missing $WinSwConfig" }

try {
    [xml](Get-Content -LiteralPath $WinSwConfig -Raw) | Out-Null
} catch {
    throw "Invalid WinSW XML ($WinSwConfig): $($_.Exception.Message)"
}

$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) { throw "Python was not found on PATH" }

$BackendUrlLiteral = ConvertTo-Json $BackendUrl -Compress
$baked = @"
# AUTO-GENERATED by installer/build.ps1 - do not edit by hand.
BAKED_BACKEND_URL = $BackendUrlLiteral
BAKED_AT_BUILD = True
"@
Set-Content -Path $BakedFile -Value $baked -Encoding UTF8
Write-Host "==> Wrote $BakedFile"

New-Item -ItemType Directory -Force -Path $DistDir | Out-Null
$pyinstallerOut = Join-Path $DistDir "onevo-connector.exe"
if (Test-Path $pyinstallerOut) { Remove-Item $pyinstallerOut -Force }

Write-Host "==> PyInstaller..."
Push-Location $ConnectorRoot
try {
    & python -m PyInstaller --noconfirm --clean --distpath $DistDir --workpath (Join-Path $DistDir "build") $SpecFile
    if ($LASTEXITCODE -ne 0) {
        throw "PyInstaller build failed (exit $LASTEXITCODE). Ensure pip install -r requirements-build.txt was run."
    }
} finally {
    Pop-Location
}
if (-not (Test-Path $pyinstallerOut)) {
    throw "PyInstaller build failed. Expected output: $pyinstallerOut"
}
Write-Host "==> Built $pyinstallerOut"

$iscc = Find-ISCC
Write-Host "==> Inno Setup: $iscc"
& $iscc $IssFile
if ($LASTEXITCODE -ne 0) { throw "Inno Setup failed (exit $LASTEXITCODE)" }

$verLine = Select-String -Path $IssFile -Pattern '#define AppVersion "([^"]+)"' | Select-Object -First 1
$version = if ($verLine) { $verLine.Matches.Groups[1].Value } else { "1.0.0" }
$setup = Join-Path $DistDir "ONEVO-Connector-Setup-$version.exe"
if (-not (Test-Path $setup)) { throw "Expected installer not found: $setup" }

Write-Host ""
Write-Host "OK  $setup"
Write-Host "    Size: $([math]::Round((Get-Item $setup).Length / 1MB, 1)) MB"
Write-Host "    Copy this file where ConnectorInstaller__Path points (or leave in connector/dist for Docker)."
