#!/bin/sh
set -eu

VERSION="$(python3 -c "import json; print(json.load(open('/src/version.json'))['connector'])")"
# Derived, not read as a second field - avoids version.json needing two
# hand-kept-in-sync values (connector version + installerFile name).
INSTALLER_FILE="ONETIX-Connector-Setup-${VERSION}.exe"
BACKEND_URL="${CONNECTOR_BUILD_BACKEND_URL:-http://localhost:8081}"
WORK_ROOT=/work
CONNECTOR_ROOT="$WORK_ROOT/connector"
OUTPUT_FILE="/output/$INSTALLER_FILE"
METADATA_FILE=/output/.installer-build.json

rm -rf "$WORK_ROOT"
mkdir -p "$WORK_ROOT" /output
cp -a /src/connector "$CONNECTOR_ROOT"
mkdir -p "$CONNECTOR_ROOT/dist" "$CONNECTOR_ROOT/installer/tools"
cp /toolchain/files/ffmpeg.exe "$CONNECTOR_ROOT/installer/tools/ffmpeg.exe"
cp /toolchain/files/WinSW-x64.exe "$CONNECTOR_ROOT/installer/tools/WinSW-x64.exe"

python3 - "$CONNECTOR_ROOT/app/baked_config.py" "$BACKEND_URL" "$VERSION" <<'PY'
import pathlib, sys
pathlib.Path(sys.argv[1]).write_text(
    '# AUTO-GENERATED by Docker installer builder.\n'
    f'BAKED_BACKEND_URL = {sys.argv[2]!r}\n'
    f'BAKED_VERSION = {sys.argv[3]!r}\n'
    'BAKED_AT_BUILD = True\n',
    encoding='utf-8',
)
PY

FINGERPRINT="$({
  printf 'version=%s\nbackendUrl=%s\n' "$VERSION" "$BACKEND_URL"
  find "$CONNECTOR_ROOT/app" "$CONNECTOR_ROOT/installer" \
       "$CONNECTOR_ROOT/onevo_launcher.py" "$CONNECTOR_ROOT/requirements.txt" \
       "$CONNECTOR_ROOT/requirements-build.txt" \
       -type f ! -path '*/dist/*' -print0 \
    | sort -z | xargs -0 sha256sum
} | sha256sum | awk '{print $1}')"

if [ -s "$OUTPUT_FILE" ] && [ -s "$METADATA_FILE" ]; then
  ACTUAL_SHA="$(sha256sum "$OUTPUT_FILE" | awk '{print $1}')"
  if jq -e \
      --arg version "$VERSION" --arg file "$INSTALLER_FILE" \
      --arg fingerprint "$FINGERPRINT" --arg sha "$ACTUAL_SHA" \
      '.version == $version and .installerFile == $file and
       .fingerprint == $fingerprint and .sha256 == $sha' \
      "$METADATA_FILE" >/dev/null; then
    echo "==> Installer is current: $OUTPUT_FILE"
    exit 0
  fi
fi

echo "==> Building ONETIX connector $VERSION in Docker (Wine)..."
WIN_CONNECTOR='Z:\work\connector'
xvfb-run -a wine64 'C:\Python311\python.exe' -m PyInstaller \
  --noconfirm --clean \
  --distpath "${WIN_CONNECTOR}\\dist" \
  --workpath "${WIN_CONNECTOR}\\dist\\build" \
  "${WIN_CONNECTOR}\\installer\\onevo-connector.spec"
wineserver -w

# /DAppVersion pins the compiled installer's version to the SAME version.json
# value used for the output filename below - this is the single place the
# two are kept in sync, so a bumped version.json can never silently compile
# an installer whose internal AppVersion still says the old number.
xvfb-run -a wine64 'C:\InnoSetup\ISCC.exe' \
  "/DAppVersion=${VERSION}" \
  "${WIN_CONNECTOR}\\installer\\onevo-connector.iss"
wineserver -w

BUILT_FILE="$CONNECTOR_ROOT/dist/$INSTALLER_FILE"
test -s "$BUILT_FILE"
TEMP_OUTPUT="/output/.${INSTALLER_FILE}.tmp"
cp "$BUILT_FILE" "$TEMP_OUTPUT"
ACTUAL_SHA="$(sha256sum "$TEMP_OUTPUT" | awk '{print $1}')"
SIZE_BYTES="$(wc -c < "$TEMP_OUTPUT" | tr -d ' ')"

python3 - "$METADATA_FILE.tmp" "$VERSION" "$INSTALLER_FILE" "$BACKEND_URL" \
  "$FINGERPRINT" "$ACTUAL_SHA" "$SIZE_BYTES" <<'PY'
import datetime, json, pathlib, sys
path, version, name, url, fingerprint, sha, size = sys.argv[1:]
payload = {
    'version': version,
    'installerFile': name,
    'backendUrl': url,
    'fingerprint': fingerprint,
    'sha256': sha,
    'sizeBytes': int(size),
    'builtAtUtc': datetime.datetime.now(datetime.timezone.utc).isoformat(),
    'builder': 'docker-wine',
}
pathlib.Path(path).write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
PY

mv -f "$TEMP_OUTPUT" "$OUTPUT_FILE"
mv -f "$METADATA_FILE.tmp" "$METADATA_FILE"
echo "==> Installer ready: $OUTPUT_FILE ($SIZE_BYTES bytes, sha256=$ACTUAL_SHA)"
